[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    bblanchon/ArduinoJson@^7.0.0
    256dpi/MQTT@^2.5.2
    arduino-libraries/NTPClient@^3.2.1

build_flags =
    -DCORE_DEBUG_LEVEL=3
